### ISSUE TITLE
UnityEditor systematically crashes when compiling scripts

### ISSUE THREAD

**Issue by schembrimax** [consulo/UnityEditorConsuloPlugin#11]
Hi I discovered this plugin and Consulo in the past few days and I really love it. But it's nearly impossible for me to work with it due to the numerous crashes (I'm using UnityEditorConsuloPlugin2017.2.dll) some of which are systematic. For example when I modify a script in Consulo and switch to the Unity Editor it starts to compile the scripts. If I switch back to consulo when Unity is still compiling the scripts the UnityEditor crashes systematically. In those cases I get the following error in Consulo (translation for the first line is more or less the following: "Connection in progress is forcibly interrupted by the remote host:"

Connessione in corso interrotta forzatamente dall'host remoto: Connessione in corso interrotta forzatamente dall'host remoto
java.io.IOException: Connessione in corso interrotta forzatamente dall'host remoto
	at sun.nio.ch.SocketDispatcher.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:192)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
	at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:288)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1106)
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:373)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:123)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at java.lang.Thread.run(Thread.java:745)

**Comment by VISTALL** [comment]
Hi. It's exception when Unity client disconnected abnormally (while connection with Consulo).

Without UnityEditorConsuloPlugin no crashes? Or maybe it's crashed while active debug ?

Thanks

**Comment by schembrimax** [comment]
Hi, thanks for the flash answer :-)
I haven't used the debugger yet so I don't think that's the problem.
I've made a few tests to give you more details. I've tried to uncheck the "Editor Attaching" option in unity external tools, but I still experience the crash. I've also tried to edit script files in consulo while configuring Unity to work with MonoDevelop (so as to avoid Unity connecting to Consulo) and in this case I don't get any crash.
I don't know if it can help but windows tell me that it is a win32 exception. May it be a problem of interaction between 64/32 bit processes ?

Thanks again for your support

**Comment by VISTALL** [comment]
No, it's not bitness problem. Consulo interact with Unity via TCP protocol (simple rest api).

Delete **UnityEditorConsuloPlugin2017.2.dll** and test without it (this plugin provide double-click handler & console message handling & tests).

For now i have no idea what is it. It's problem on Unity side, but need found where.

Unity crashed without Unity Reporter? (unity almost all time handle critical errors, and show their error handler, where you can send report to their tracker)

Can you find crash log? (you can found it in their error reporter, or by path C:\Users\%USER%\AppData\Local\Unity\Editor)

Thanks

**Comment by schembrimax** [comment]
Deleting the dll it no longer crashes. Strangely I have no trace of crash report from Unity. Nothing in the Log file and, most importantly I don't get the usual Bug Report Window with which I can send crash information to Unity.

Anyway thanks very much for your quick help. Please let me know if  you manage to understand more about this issue.

**Comment by VISTALL** [comment]
Can you say your workspace setup ?(os, unity)

Thanks

**Comment by schembrimax** [comment]
Windows 10 / Unity 2017.2 (I've just updated to Unity 2017.3 but still get the same problem)

**Comment by VISTALL** [comment]
Win 64 bit?  Debug works without this plugin (just clarify)

**Comment by schembrimax** [comment]
Yes Win 64
